Сделал задания по 6й лекции
js-tasks-ru/js-20210309-2_gluknik pull request #4
Opened 2021-04-02 13:44 UTC by gluknik

2021-04-03 16:14 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    if (event.currentTarget.dataset.order === targetOrder) {
пожалуйста используйте `closest` метод, посмотрите разбор этого компонента

2021-04-03 16:16 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.tooltip !== this.currentText) {
здесь сначала следует проверить что это тот элемент который нас интересует
```
const element = event.target.closest('[data-tooltip]');
```

2021-04-03 16:17 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.element.style.left = `${event.clientX + 10}px`;
10 хорошо бы вынести в переменную с осознанным имененм

2021-04-03 16:17 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.tooltip !== undefined) {
good 👍

2021-04-03 16:18 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      event.target.addEventListener('pointerout', this.onPointerOut);
`pointerout` лучше навесить на `document`

2021-04-03 16:18 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.remove();
обязательно нужно снять глобальные обработчики (обработчики навешенные на `document`)

2021-04-03 16:19 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-04-04 18:09 UTC, gluknik commented
все поправил :)

2021-04-05 08:59 UTC, dosandk approved these changes
good 👍

2021-04-05 08:59 UTC, merged